const CORE = {
  "Wayfinding": [
    "Navigation",
    "Orientation",
    "Getting lost",
    "Exploration",
    "Legibility",
    "Landmarks",
    "Dead reckoning",
    "Pilgrimage"
  ],
  "Spatial configuration": [
    "Connectivity",
    "Visibility",
    "Thresholds",
    "Depth",
    "Adjacency",
    "Boundaries",
    "Centrality",
    "Permeability"
  ],
  "Space syntax": [
    "Integration",
    "Choice",
    "Intelligibility",
    "Axiality",
    "Segment analysis",
    "Isovists",
    "Configuration",
    "Natural movement"
  ],
  "Architecture": [
    "Shelter",
    "Habitation",
    "Materiality",
    "Craft",
    "Domesticity",
    "Atmosphere",
    "Construction",
    "Place"
  ],
  "Human–computer interaction": [
    "Affordances",
    "Embodiment",
    "Interaction",
    "Feedforward",
    "Participation",
    "Discoverability",
    "Usability",
    "Attention"
  ],
  "Virtual environments": [
    "Immersion",
    "Presence",
    "Simulation",
    "Digital twins",
    "Mixed reality",
    "Telepresence",
    "Persistence",
    "Avatars"
  ],
  "Narrative": [
    "Story",
    "Journey",
    "Memory",
    "Myth",
    "Character",
    "Perspective",
    "Framing",
    "Plot"
  ],
  "Innovation": [
    "Serendipity",
    "Paradigm shifts",
    "Experimentation",
    "Failure",
    "Diffusion",
    "Invention",
    "Adoption",
    "Recombination"
  ],
  "Complexity": [
    "Emergence",
    "Self-organisation",
    "Distributed intelligence",
    "Feedback",
    "Resilience",
    "Adaptation",
    "Nonlinearity",
    "Phase transition"
  ],
  "Space habitation": [
    "Rockets",
    "Mars stations",
    "Moon settlements",
    "Orbital habitats",
    "Closed ecologies",
    "Space architecture",
    "Long-duration missions",
    "Extraterrestrial wayfinding"
  ],
  "Deployable structures": [
    "Scissor mechanisms",
    "Origami",
    "Folding",
    "Tensegrity",
    "Kinematics",
    "Transformation",
    "Deployability",
    "Retractability"
  ],
  "Movement": [
    "Pedestrians",
    "Cyclists",
    "Crowds",
    "Flows",
    "Desire lines",
    "Mobility",
    "Rhythm",
    "Navigation behaviour"
  ]
};
const BORROW = [
  "Evolution",
  "Morphogenesis",
  "Homeostasis",
  "Symbiosis",
  "Ecological niches",
  "Taxonomy",
  "Grammar",
  "Pragmatics",
  "Metaphor",
  "Counterpoint",
  "Cadence",
  "Dissonance",
  "Harmony",
  "Camouflage",
  "Reconnaissance",
  "Logistics",
  "Attrition",
  "Control theory",
  "Game theory",
  "Information theory",
  "Signal",
  "Markets",
  "Scarcity",
  "Incentives",
  "Collective action",
  "Ritual",
  "Semiotics",
  "Phenomenology",
  "Epistemology",
  "Causality",
  "Reductionism",
  "Abduction",
  "Morphology",
  "Diffusion of innovations",
  "Path dependence",
  "Institutional memory",
  "Cognitive dissonance",
  "Bayesian inference",
  "Embodied cognition",
  "Distributed cognition",
  "Network effects",
  "Phase space",
  "Criticality",
  "Recursion",
  "Narrative transportation",
  "Social learning",
  "Cultural evolution",
  "Boundary objects"
];
const GRIST = [
  "Compass",
  "Beehive",
  "Soap bubble",
  "Garden shed",
  "Bell-ringing",
  "Knitting",
  "Spider web",
  "Violin",
  "Hourglass",
  "Rope",
  "Mirror",
  "Bridge",
  "Kettle",
  "Umbrella",
  "Mushroom",
  "Slime mould",
  "Origami",
  "Tree",
  "Leaf",
  "Shell",
  "Clock",
  "Key",
  "Lantern",
  "Camera",
  "Net",
  "Basket",
  "Feather",
  "Tent",
  "Caravan",
  "Bread",
  "Mask",
  "Bottle",
  "Dry-stone walling",
  "Sailing",
  "Pottery",
  "Weaving",
  "Glassblowing",
  "Gardening",
  "Bread-making",
  "Map-folding",
  "Paper aeroplane",
  "Canal lock",
  "Lighthouse",
  "Bird's nest",
  "Clock-making",
  "Beekeeping",
  "Stage magic",
  "Jigsaw puzzle"
];
